# Generated by Django 5.2.7 on 2025-10-08 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Если включено — это приятная (вознаграждающая) привычка.",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="От 1 до 7 дней. Нельзя реже, чем раз в 7 дней.",
                        verbose_name="Периодичность (дней)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Текстовое вознаграждение. Не заполняется, если указана связанная приятная привычка.",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration_sec",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Не более 120 секунд.",
                        verbose_name="Время на выполнение (сек)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Если включено — привычка видна в общем списке.",
                        verbose_name="Публичная",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Должна ссылаться на ПРИЯТНУЮ привычку. Используется для полезных привычек.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("duration_sec__lte", 120)),
                        name="habit_duration_le_120",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("periodicity_days__gte", 1), ("periodicity_days__lte", 7)
                        ),
                        name="habit_periodicity_between_1_and_7",
                    ),
                ],
            },
        ),
    ]
